import type { Metadata } from 'next';
import { Open_Sans, Roboto_Slab } from 'next/font/google';
import { PreloadWrapper } from '@/components/PreloadWrapper';
import { Header } from '@/components/layouts/Header';
import { Footer } from '@/components/layouts/Footer';

import '@/assets/styles/main.scss';

const openSans = Open_Sans({
  weight: ['300', '400', '600', '700', '800'], // выбери нужные веса
  subsets: ['latin'],
  variable: '--font-open-sans',
  display: 'swap',
});

const robotoSlab = Roboto_Slab({
  weight: ['300', '400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto-slab',
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    template: '%s | Comfort Zone',
    default: 'Comfort Zone',
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${robotoSlab.variable}`}>
        <div className="app">
          <Header />
          <main className="page-content">
            <PreloadWrapper>{children}</PreloadWrapper>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
